### ISSUE TITLE
My findings

### ISSUE THREAD

**Issue by svdo** [mmzsource/mxmmz#1]
Hi @mmzsource! I like your approach to a simple website. I cloned the source code and tried it out. Here are a couple of findings:

- After cloning, when running `gen.clj`, I get this error message:
  ```
  java.io.FileNotFoundException: publish/index.html (No such file or directory) [at /[redacted]/mxmmz/gen.clj, line 112, column 5]
  ```
  It appears the script expects the folder `publish` to exist, but after cloning it doesn't yet.
- I noticed `remedy.css` and your comment about `line-sizing`. You made a typo however on [line 16](https://github.com/mmzsource/mxmmz/blob/4e90e71cc6a3b81fcad6f6c8c14079ac62787af9/site/remedy.css#L16) however: the -h- is missing. This directive currently doesn't do anything.

Thanks for sharing!!

**Comment by mmzsource** [comment]
Good catch, thank you. I didn't clone it after starting working on it. Should be fixed now. now you can `./gen.clj` directly after cloning and `open publish/index.html` immediately afterwards.
